### ISSUE TITLE
how to install

### ISSUE THREAD

**Issue by Layty** [kdcro101/vscode-favorites#12]
I have install in win7 x86, but it tells me
` command 'favorites.addToFavorites' not found` 
what else should I do

**Comment by Layty** [comment]
yes,  I can see the menu in the vscode in my office computer (win7 x86)
1. first I try by right-clicking,and there is no reaction
2. then I try to press `Ctrl+shift+p` to select `add to favorites`  command ,but then the vscode tell me there is no command.

But now it works well in my own computer,it is win7 x64.
so I wonder if it can't work well in win7 x86,or I should install other package?

**Comment by kdcro101** [comment]
@Layty ,

Try reinstall extension (uninstall -> restart vscode  ->  install ).
Are you using latest vscode version?
Can you post `Developer tools` output (Help -> Toggle Developer Tools)?

**Comment by Layty** [comment]
onle one floder is ok, some floder is bad ,both of their name only have `a~z` character


![animation](https://user-images.githubusercontent.com/14368090/45364093-d50b8e80-b60b-11e8-9fb7-a4a4851a8ab5.gif)

**Comment by kdcro101** [comment]
@Layty ,

Please do following:
1. Close vscode
2. Open vscode 
3. add something to favorites 
4. copy or screenshot Developer tools output.

**Comment by Layty** [comment]
yes, I have try  reset vscode and reinstall. It  doesn't work.

when I click `add to fav`,there is no message, then I try to click the `creat a group`
show that
```
Error: command 'favorites.group.create' not found
    at t._tryExecuteCommand (workbench.main.js:sourcemap:3019)
    at workbench.main.js:sourcemap:3019
    at n.Class.derive._oncancel.then (workbench.main.js:sourcemap:161)
    at t.executeCommand (workbench.main.js:sourcemap:3019)
    at t.run (workbench.main.js:sourcemap:1369)
    at t.run (workbench.main.js:sourcemap:1370)
    at t.e.runAction (workbench.main.js:sourcemap:236)
    at t.e.run (workbench.main.js:sourcemap:236)
    at t.run (workbench.main.js:sourcemap:5237)
    at t.onClick (workbench.main.js:sourcemap:1444)
    at Immediate.<anonymous> (workbench.main.js:sourcemap:872)
    at runCallback (timers.js:789)
    at tryOnImmediate (timers.js:751)
    at processImmediate [as _immediateCallback] (timers.js:722)
```

**Comment by Layty** [comment]
When I use `Ctrl+shift+p` to call `add to favo`
show 
```
workbench.main.js:sourcemap:2407 Error: command 'favorites.addToFavorites' not found
    at t._tryExecuteCommand (workbench.main.js:sourcemap:3019)
    at workbench.main.js:sourcemap:3019
    at n.Class.derive._oncancel.then (workbench.main.js:sourcemap:161)
    at t.executeCommand (workbench.main.js:sourcemap:3019)
    at t.run (workbench.main.js:sourcemap:1369)
    at t.run (workbench.main.js:sourcemap:1370)
    at workbench.main.js:sourcemap:2968
```


![animation](https://user-images.githubusercontent.com/14368090/45365330-dd18fd80-b60e-11e8-8384-9b6a4e0f9bbd.gif)

**Comment by Layty** [comment]
here is my vscode version
版本: 1.27.1 (user setup)
提交: 5944e81f3c46a3938a82c701f96d7a59b074cfdc
日期: 2018-09-06T09:21:18.328Z
Electron: 2.0.7
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
x64

**Comment by kdcro101** [comment]
@Layty,

I think problem is in some extension that is initialized before this one, that breaks initialization on 'Favorites'.
Commands are registred early in code so message `command not found` would lead me to think that extension is not fully loaded.

Please, check `Developer tools` for any error before `command not found`.

Try this steps:

- uninstall favorites
- check for errors from any other extension in `developer tools`
- uninstall all unnecessary and suspicious  extensions
- reload
- install `favorites` extension
- try using it


If this doesn't helps, try reinstalling vscode + reinstall all externsions you use, then try again.

What extensions do you use at work that you do not use at home? That could be culprit.

**Comment by Layty** [comment]
I am sorry , you may ignore that 
1. In my home computer,only one floder is work well ,others is bad.

Now I try to do in my office vscode.
1. No other extensions but favorites
2. I have reinstall vscod 
3. version is 
```
Version: 1.27.1 (user setup)
Commit: 5944e81f3c46a3938a82c701f96d7a59b074cfdc
Date: 2018-09-06T09:21:10.934Z
Electron: 2.0.7
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: ia32
```
note:
1. It works well also once ,that after I reset the computer ,reinstall vscode and the `favo`,
2. but other floder is bad too 
3. I close other and open the first floder is ok well.
4. then i copy the setting to other floder,bad too.
5. I delete other files but leave one file in the first floder
6. It works bad in the first floder
7. Now ,all of them work bad.
----------
yestoday I install vscode in c , now I install in D:\
In the console,there is no err before I click the add menu.then I click the add group.(because add file norespose),show errs:
```
/D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1411  INFO no standard startup: not just one text editor
workbench.main.js:sourcemap:2407 Error: command 'favorites.group.create' not found
    at t._tryExecuteCommand (file:///D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3019:717)
    at file:///D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3019:572
    at Object.g [as _notify] (file:///D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:154:729)
    at Object.enter (file:///D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:158:61)
    at n.Class.derive._oncancel._run (file:///D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:159:902)
    at n.Class.derive._oncancel._completed (file:///D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:159:343)
    at l (file:///D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:162:855)
    at n.Class.derive.join.r.forEach.j.then.o.(anonymous function) (file:///D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:163:45)
    at Object.g [as _notify] (file:///D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:154:729)
    at Object.enter (file:///D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:158:61)
    at n.Class.derive._oncancel._run (file:///D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:159:902)
    at n.Class.derive._oncancel._completed (file:///D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:159:343)
    at l (file:///D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:162:855)
    at n.Class.derive.join.r.forEach.j.then.o.(anonymous function) (file:///D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:163:45)
    at Object.g [as _notify] (file:///D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:154:729)
    at Object.enter (file:///D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:158:61)
    at n.Class.derive._creator._run (file:///D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:159:902)
    at n.Class.derive._creator._completed (file:///D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:159:343)
    at Object.g [as _notify] (file:///D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:154:729)
    at Object.enter (file:///D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:158:61)
    at n.Class.derive._oncancel._run (file:///D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:159:902)
    at n.Class.derive._oncancel._completed (file:///D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:159:343)
    at e.resolveOk (file:///D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3166:685)
    at e._receiveReply (file:///D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3234:965)
    at e._receiveOneMessage (file:///D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3233:519)
    at file:///D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3232:74
    at e.fire (file:///D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:175:76)
    at a (file:///D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:311:740)
    at Socket.n._socketDataListener (file:///D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:311:959)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
t.onDidNotificationChange @ workbench.main.js:sourcemap:2407
(anonymous) @ workbench.main.js:sourcemap:2407
e.fire @ workbench.main.js:sourcemap:175
t.notify @ workbench.main.js:sourcemap:2400
t.error @ workbench.main.js:sourcemap:3483
(anonymous) @ workbench.main.js:sourcemap:4967
e.fire @ workbench.main.js:sourcemap:175
(anonymous) @ workbench.main.js:sourcemap:236
v @ workbench.main.js:sourcemap:155
enter @ workbench.main.js:sourcemap:158
_run @ workbench.main.js:sourcemap:159
_chainedError @ workbench.main.js:sourcemap:159
n @ workbench.main.js:sourcemap:157
then @ workbench.main.js:sourcemap:160
enter @ workbench.main.js:sourcemap:157
_run @ workbench.main.js:sourcemap:159
_setCompleteValue @ workbench.main.js:sourcemap:159
g @ workbench.main.js:sourcemap:154
enter @ workbench.main.js:sourcemap:158
_run @ workbench.main.js:sourcemap:159
_completed @ workbench.main.js:sourcemap:159
l @ workbench.main.js:sourcemap:162
n.Class.derive.join.r.forEach.j.then.o.(anonymous function) @ workbench.main.js:sourcemap:163
g @ workbench.main.js:sourcemap:154
enter @ workbench.main.js:sourcemap:158
_run @ workbench.main.js:sourcemap:159
_completed @ workbench.main.js:sourcemap:159
l @ workbench.main.js:sourcemap:162
n.Class.derive.join.r.forEach.j.then.o.(anonymous function) @ workbench.main.js:sourcemap:163
g @ workbench.main.js:sourcemap:154
enter @ workbench.main.js:sourcemap:158
_run @ workbench.main.js:sourcemap:159
_completed @ workbench.main.js:sourcemap:159
g @ workbench.main.js:sourcemap:154
enter @ workbench.main.js:sourcemap:158
_run @ workbench.main.js:sourcemap:159
_completed @ workbench.main.js:sourcemap:159
e.resolveOk @ workbench.main.js:sourcemap:3166
e._receiveReply @ workbench.main.js:sourcemap:3234
e._receiveOneMessage @ workbench.main.js:sourcemap:3233
(anonymous) @ workbench.main.js:sourcemap:3232
e.fire @ workbench.main.js:sourcemap:175
a @ workbench.main.js:sourcemap:311
n._socketDataListener @ workbench.main.js:sourcemap:311
emitOne @ events.js:116
emit @ events.js:211
addChunk @ _stream_readable.js:263
readableAddChunk @ _stream_readable.js:250
Readable.push @ _stream_readable.js:208
onread @ net.js:594

```

**Comment by kdcro101** [comment]
@Layty,

Post here `settings.json` form `.vscode` directory inside your workspace.

**Comment by Layty** [comment]
Now I have write in  user setting and workspace setting ,both error.
1. user setting 
2. work space setting
3. both 1and 2

**Comment by kdcro101** [comment]
@Layty,

Can you copy and paste, here, contents of `settings.json`  from `.vscode` directory

**Comment by Layty** [comment]
now I found a work well floder , 
show 
```
user
{
    "explorer.confirmDelete": false,
    "workbench.colorTheme": "Quiet Light",
    "files.autoGuessEncoding": true,
    "editor.fontFamily": "'Ubuntu Monospaced',Consolas, 'Courier New', monospace",
}
workspace
{
    "favorites.sortDirection": "ASC",
    "favorites.groupsFirst": true
}
```

and I creat a new floder ,just one file 
A
--A.c 
--.vscode  copy from the ok floder

**Comment by Layty** [comment]
for the new floder `A`,there is no .vscode, and It works  bad.
then I copy the .vscode from the ok floder ,it does't work

**Comment by xuejianxianzun** [comment]
Update: I have no problem.

**Comment by kdcro101** [comment]
@xuejianxianzun ,


Can you, please, post workspace `settings.json` that is located in your project folder (`project_directory/.vscode/settings.json`)?

I suspect special unicode characters (chinese?).

**Comment by xuejianxianzun** [comment]
I understand the reasons for my problems. When I tested this extension, I did not open the workspace, just opened a file. There is no problem in workspace.

In fact, I hope to have a global favorites. It seems that I should achieve it through other ways.

I'm very sorry to bother you, thank you.

**Comment by kdcro101** [comment]
@xuejianxianzun, no problem! 
Thank you for helping me realizing what problem is. I will try to make some changes to prevent this scenario.

**Comment by kdcro101** [comment]
@Layty ,

Does @xuejianxianzun  solution works for you?

**Comment by Layty** [comment]
@kdcro101  
No，you can see the gif  I have sent, all of them are in a floder.
But now I dont know why everything is ok.....in my home computer .I do nothing.

**Comment by Layty** [comment]
Only reset my computer today（yestoday I closed it，now I power on and without reinstall `favo`） ，I will try tomorry moning. It is so strange.

**Comment by kdcro101** [comment]
@Layty ,

I will close this issue. Reopen if you still have problems.

**Comment by Layty** [comment]
ok， It works well Now

**Comment by kdcro101** [comment]
Glad to hear everything went well!
