### ISSUE TITLE
Doesn't work VS Code 1.27.2 on macOs 10.12.6

### ISSUE THREAD

**Issue by evanre** [kdcro101/vscode-favorites#15]
Sorry if I miss understanding something, but it doesn't work at all (in VS Code 1.27.2 on macOs 10.12.6).

I've installed it from marketplace, reloaded VS Code. "Heart" tab appears in the sidebar, but I can't add anything to it. Also it absent in context menu.

Thanks for help

**Comment by kdcro101** [comment]
@evanre,

Thank you for your feedback.

Can you, please, post output of `console`. You can access it via `Help -> Toggle Developer Tools`

**Comment by evanre** [comment]
Hi, @kdcro101, thanks for fast response. 
Here is console output on fresh load:

>  INFO no standard startup: not just one text editor
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:276 [Extension Host] [34m[2018-09-29 14:35:04.270] [TRACE] extension - [39minitialize
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:276 [Extension Host] [34m[2018-09-29 14:35:04.272] [TRACE] extension - [39mgetConfiguration
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:276 [Extension Host] [36m[2018-09-29 14:35:04.272] [DEBUG] extension - [39mgetConfiguration { onStartup: true,
  dontShowPortAlreadyInUseError: false,
  port: 52698,
  host: '127.0.0.1' }
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:276 [Extension Host] [34m[2018-09-29 14:35:04.273] [TRACE] extension - [39mstartServer
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:276 [Extension Host] [34m[2018-09-29 14:35:04.273] [TRACE] Server - [39mconstructor
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:276 [Extension Host] [34m[2018-09-29 14:35:04.273] [TRACE] StatusBarItem - [39mconstructor
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:276 [Extension Host] [34m[2018-09-29 14:35:04.274] [TRACE] Server - [39msetPort 52698
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:276 [Extension Host] [34m[2018-09-29 14:35:04.274] [TRACE] Server - [39msetHost 127.0.0.1
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:276 [Extension Host] [34m[2018-09-29 14:35:04.274] [TRACE] Server - [39msetDontShowPortAlreadyInUseError false
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:276 [Extension Host] [34m[2018-09-29 14:35:04.274] [TRACE] Server - [39mstart false
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:276 [Extension Host] [34m[2018-09-29 14:35:04.274] [TRACE] Server - [39misOnline
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:276 [Extension Host] [36m[2018-09-29 14:35:04.274] [DEBUG] Server - [39misOnline? false
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:276 [Extension Host] [32m[2018-09-29 14:35:04.274] [INFO] Server - [39mStarting server
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:276 [Extension Host] [34m[2018-09-29 14:35:04.275] [TRACE] Server - [39mgetPort 52698
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:276 [Extension Host] [34m[2018-09-29 14:35:04.275] [TRACE] Server - [39mgetHost NaN
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:276 [Extension Host] [34m[2018-09-29 14:35:04.276] [TRACE] StatusBarItem - [39msetServer
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:276 [Extension Host] [34m[2018-09-29 14:35:04.276] [TRACE] StatusBarItem - [39mhandleEvents
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:276 [Extension Host] [34m[2018-09-29 14:35:04.285] [TRACE] Server - [39monServerListening
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:276 [Extension Host] [34m[2018-09-29 14:35:04.285] [TRACE] Server - [39msetOnline true
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:276 [Extension Host] [34m[2018-09-29 14:35:04.285] [TRACE] StatusBarItem - [39monReady
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1411   ERR Unable to write to Workspace Settings because no workspace is opened. Please open a workspace first and try again.: Error: Unable to write to Workspace Settings because no workspace is opened. Please open a workspace first and try again.
    at new t (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4110:511)
    at e.wrapError (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4114:354)
    at e.resolveAndValidate (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4117:732)
    at e.doWriteConfiguration (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4111:372)
    at Object.factory (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4111:105)
    at t.e.consume (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:197:264)
    at e.queue (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:197:51)
    at new n.Class.derive._oncancel (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:161:625)
    at t.e.queue (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:196:969)
    at e.writeConfiguration (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4111:79)
    at t.writeConfigurationValue (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4138:847)
    at t.updateValue (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4128:107)
    at e.writeConfiguration (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3176:95)
    at e.$updateConfigurationOption (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3175:760)
    at e._doInvokeHandler (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3235:593)
    at e._invokeHandler (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3235:311)
    at e._receiveRequest (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3234:129)
    at e._receiveOneMessage (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3233:270)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3232:74
    at e.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:175:76)
    at a (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:311:740)
    at Socket.n._socketDataListener (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:311:959)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)

**Comment by kdcro101** [comment]
@evanre ,

I think problem is that you haven't opened workspace/folder. Extension needs workspace settings to be available. That is where extension store data about favorite items.

Try this:
1. open workspace
2. right click any item in `File explorer` (check image 1) and  select `add to favorites`
3. check item you added in `Favorites explorer` (heart icon on activity bar)  or `Favorites` subview in `File explorer` (check image 2)

## Image 1
![](https://raw.githubusercontent.com/kdcro101/vscode-favorite-items/master/preview/adding.jpg)

## Image 2
![](https://raw.githubusercontent.com/kdcro101/vscode-favorite-items/master/preview/using.jpg)

Please, let me know how it went.

**Comment by evanre** [comment]
I'm not familiar with VS Code, "workspace" it's some kind of a project folder?
Does it mean that favorite files working only across particular workspace? I just want to launch VS Code, and open tab with saved favorite files on my computer.

**Comment by kdcro101** [comment]
When you open folder in vscode (`File->Open folder`), workspace is created.
You can have workspaces with multiple `root` folders (multiroot workspaces) to encapsulate multiple projects in single workspace (`File->Add Folder to Workspace`).

With this extension you can add as favorites, items within workspace or external resources (file/directory) - out of workspaces,  to be quickly accessible while working in workspace.

Purpose of this extension is to ease access to resources when file system structure of workspace is complex enough to require constant scrolling and/or expanding/collapsing of directory structure.

I guess you need some sort of favorite files/ projects that are not related to workspace.

Try: 

[Project manager](https://marketplace.visualstudio.com/items?itemName=alefragnani.project-manager)

I hope it helps.
